/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Diego
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/nahIcon.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnRegistrate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        btnEmp = new javax.swing.JButton();
        txtModo = new javax.swing.JTextField();
        lblVersion1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresa a NAH");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresa a NAH");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(63, 63, 63));
        txtUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHighlighter(null);
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 361, 50));

        btnIngresar.setBackground(new java.awt.Color(255, 0, 255));
        btnIngresar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setFocusPainted(false);
        btnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnIngresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1presionado.png"))); // NOI18N
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 100, 45));

        btnRegistrate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        btnRegistrate.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnRegistrate.setText("Registrate");
        btnRegistrate.setFocusPainted(false);
        btnRegistrate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrate.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        btnRegistrate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1presionado.png"))); // NOI18N
        getContentPane().add(btnRegistrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 110, 45));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        txtContrasena.setBackground(new java.awt.Color(73, 69, 69));
        txtContrasena.setForeground(new java.awt.Color(255, 255, 255));
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 361, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 86)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAH");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Iniciar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sesion");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 86)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("|");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 60, -1));

        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnEmpLog.png"))); // NOI18N
        btnAdmin.setFocusPainted(false);
        btnAdmin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnEmpLog.png"))); // NOI18N
        btnAdmin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnEmpLogPresionado.png"))); // NOI18N
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 50, 50));

        btnEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAdmLog.png"))); // NOI18N
        btnEmp.setFocusPainted(false);
        btnEmp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAdmLog.png"))); // NOI18N
        btnEmp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAdmLogPresionado.png"))); // NOI18N
        getContentPane().add(btnEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 50, 50));

        txtModo.setEditable(false);
        txtModo.setBackground(new java.awt.Color(51, 51, 51));
        txtModo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txtModo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtModo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 100, -1));

        lblVersion1.setForeground(new java.awt.Color(255, 255, 255));
        lblVersion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.png"))); // NOI18N
        lblVersion1.setText("ver. 1.0");
        lblVersion1.setFocusPainted(false);
        lblVersion1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblVersion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 100, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblVersion.setBackground(new java.awt.Color(255, 255, 255));
        lblVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblVersion.setText("ver. 1.0");
        getContentPane().add(lblVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmLogin().setVisible(true);
            }
           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdmin;
    public javax.swing.JButton btnEmp;
    public javax.swing.JButton btnIngresar;
    public javax.swing.JButton btnRegistrate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblVersion;
    public javax.swing.JButton lblVersion1;
    public javax.swing.JPasswordField txtContrasena;
    public javax.swing.JTextField txtModo;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
